server:
  port: 8002

#mybatis的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件所在路径
  type-aliases-package: com.xns.springcloud.entities     #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                  #mapper映射文件
#  configuration:
#    map-underscore-to-camel-case: true

#spring的整合
spring:
  application:
    name: servicecloud-dept     #服务名称绝对不能动
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver         #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02          #数据库名称
    username: root
    password: tian787604
    druid:
      #配置货物连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次监测，检测需要关闭的控线连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true


eureka:
  client:
    service-url:
#      单机
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: servicecloud-dept8002
    prefer-ip-address: true    #访问路径可以显示IP地址

debug: true

info:
  app.name: xns-servicecloud
  company.name: www.xns.com
#  build.artifactId: '@project.artifactId@'
#  build.version: '@project.version@'
  build.artifactId: $project.artifactId$
  build.version: $project.version$