server:
  port: 3344
spring:
  application:
    name: servicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ybfqlt/servicecloud-config.git   #github仓库名字
